DROP TABLE KIOSK;
CREATE TABLE KIOSK(
    ITEMID NUMBER PRIMARY KEY NOT NULL,
    ITEMNAME VARCHAR2(30) NOT NULL UNIQUE,
    PRICE NUMBER NOT NULL,
    ITEMSOLDOUTCHECK VARCHAR2(3) NOT NULL CHECK(ITEMSOLDOUTCHECK IN ('Y','N')),
    ITEMINFO VARCHAR2(30),
    ITEMRECOMMEND VARCHAR2(30) CHECK(ITEMRECOMMEND IN ('추천메뉴', '일반메뉴'))
);

INSERT INTO KIOSK VALUES(01 , '아메리카노', 1600, 'Y','에스프레소','추천메뉴');
INSERT INTO KIOSK VALUES(02 , '카페라떼', 2900, 'Y','라떼','추천메뉴');
INSERT INTO KIOSK VALUES(03 , '콜드브루오리지널', 3500, 'N','콜드브루','일반메뉴');
INSERT INTO KIOSK VALUES(04 , '감자빵', 3500, 'N','베이커리','일반메뉴');

INSERT INTO KIOSK VALUES(06 , '할메가커피', 1900, 'Y','에스프레소','추천메뉴');
INSERT INTO KIOSK VALUES(07 , '메가에이드', 3900, 'Y','에이드','일반메뉴');
INSERT INTO KIOSK VALUES(08 , '유니콘프라페', 4800, 'Y','프라페','일반메뉴');
INSERT INTO KIOSK VALUES(09 , '딸기바나나스무디', 4000, 'Y','스무디','일반메뉴');
INSERT INTO KIOSK VALUES(10 , '딸기라떼', 3700, 'Y','논커피라떼','추천메뉴');


SELECT ITEMNAME, PRICE, ITEMSOLDOUTCHECK FROM KIOSK;

COMMIT;