SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY AS "계열" FROM TB_DEPARTMENT;

SELECT DEPARTMENT_NAME || '의 정원은 '|| CAPACITY ||'명 입니다.' AS "학과별 정원"  FROM TB_DEPARTMENT;

SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과' AND ABSENCE_YN ='Y' AND
SUBSTR(STUDENT_SSN,8,1) IN ('2','4');

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT CATEGORY
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
AND ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '%전주%';

----------------------------------------------------------------

SELECT DEPARTMENT_NO AS "학번",STUDENT_NAME AS "이름" , TO_CHAR(ENTRANCE_DATE, 'RRRR-MM-DD') AS "입학년도"
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '002'
ORDER BY 입학년도 ASC;

--2
















